name: (DEV) Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  wait_and_exit:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for 5 seconds
      run: sleep 5
    - name: Exit
      run: echo "Exiting after 5 seconds."
