name: (DEV) Deploy to Amazon ECS

on:
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - name: Wait for 5 seconds
      run: sleep 5
