name: K6 Load Test

on:
  push:
    branches:
      - main

jobs:
  setup_and_run_load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run curl command
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "query": "query GetPost($id: String!) { post: Post(id: $id) { ok error items { id type userId imageUrl videoUrl youtubeVideoId youtubeVideoTitle youtubeVideoTime detail status createdBy isDelete blogDetail tag user { id gender instagramId imageUrl height creator { id userId height weight bodyShape preferStyle preferBrand isHideWeight job youtubeChannelName youtubeChannelHandle youtubeChannelProfileImageUrl __typename } __typename } images { id postId url __typename } postItems { id isWear category time size product { id imageUrl brandId brand { id name nameKr __typename } name nameEn category subCategory price isSale salePrice saleLink displayName seasonType needVerify affiliateStoreId affiliateProductId productItems { id size stock status __typename } __typename } __typename } styleTags { id name code displayName displayNameEn displayNameJa __typename } ambassadorBrandId createdAt updatedAt __typename } __typename }}",
            "variables": {
              "id": "36313"
            }
          }' api-stg.onthelook.co.kr/graphql
