name: K6 Load Test

on:
  workflow_run:
    workflows: ["(DEV) Deploy to Amazon ECS"]
    branches:
      - main
    types:
      - completed

jobs:
  k6_load_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
