name: EC2 K6 Test Runner

on:
  workflow_run:
    workflows: ["(DEV) Deploy to Amazon ECS"]
    branches:
      - main
    types:
      - completed

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run K6 Load Test on EC2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0b2eaf82f5c11df40 --count 1 --instance-type t2.micro --key-name ${{ secrets.KEY_NAME }} --subnet-id ${{ secrets.SUBNET_ID }} --security-group-ids ${{ secrets.SECURITY_GROUP_ID }} --user-data file://user-data.sh --query 'Instances[0].InstanceId' --output text)
        
        aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        
        aws ec2 get-console-output --instance-id $INSTANCE_ID --output text
        
        aws ec2 terminate-instances --instance-ids $INSTANCE_ID